# Database
db.driver: com.mysql.jdbc.Driver
db.url: ${DB_TRAVELAGENCY_URL}
db.username: ${DB_TRAVELAGENCY_USER}
db.password: ${DB_TRAVELAGENCY_PASSWORD}

# Hibernate
hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
hibernate.show_sql: true
hibernate.hbm2ddl.auto: create
entitymanager.packagesToScan: org.project
data.script=insert.sql
